#!/usr/bin/env escript

-include_lib("kernel/include/file.hrl").

main(_Args) ->
    {ok, Cwd} = file:get_cwd(),
    ThisScript = filename:join([Cwd, escript:script_name()]),
    Dir = filename:dirname(ThisScript),
    CtSrc = filename:join([Dir, "ct.src"]),
    CtDst = filename:join([Dir, "bin/ct"]),
    replace(Dir, CtSrc, CtDst),
    os:cmd("chmod 755 " ++ CtDst),
    file:set_cwd(Dir),
    make:all(),
    io:format("done!\n").

replace(Dir, Src, Dst) ->
    {ok, IoSrc} = file:open(Src, [raw, read]),

    {ok, Str} = file:read(IoSrc, 99999),

    Str1 = replace_str(Str, "MOCKYMOCKERSON_INCLUDE_PATH",
                        filename:join(Dir, "include")),
    
    Str2 = replace_str(Str1, "MOCKYMOCKERSON_EBIN_PATH",
                        filename:join(Dir, "ebin")),

    file:close(IoSrc),

    {ok, IoDst} = file:open(Dst, [raw, write]),

    ok = file:write(IoDst, Str2),

    file:close(IoDst).

replace_str(Src, Old, New) ->
    re:replace(Src, Old, New, [{return,list}]).

