#!/usr/bin/env escript

main(_Args) ->
    case make:files([   rr_test,
                        "../rr.erl",
                        "../rr_lib.erl",
                        "../rr_src.erl",
                        "../rr_beam.erl",
                        "../rr_file.erl",
                        "../rr_module.erl"], [debug_info]) of
        error ->
            halt(1);
        up_to_date ->
            do_nothing
    end,
    TestCase = [escript:script_name()],
    case rr_test:run() of
        ok ->
            io:format("~p all pass!~n", [TestCase]);
        Other ->
            io:format("~p failed!~n~p", [TestCase, Other])
    end.

